version = 0.1
[default.deploy.parameters]
stack_name = "challenge-app"
resolve_s3 = false
s3_bucket = "challenge-app-jspg-2024"
s3_prefix = "challenge-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
